### ISSUE TITLE
`parse_requirements` raises exception for git+ssh://… line

### ISSUE THREAD

**Issue by stevecj** [di/pip-api#108]
When using `parse_requirements` with a file containing an entry such as
```
git+ssh://git@git.cliosoft.net/HUB/pyfpdf.git#egg=fpdf
```
it fails with an exception like
```
pip_api.exceptions.PipError: Invalid requirement: 'git+ssh://git@git.cliosoft.net/HUB/pyfpdf.git#egg=fpdf'                                                                               
It looks like a path. File 'git+ssh://git@git.cliosoft.net/HUB/pyfpdf.git#egg=fpdf' does not exist.        
```

**Comment by stevecj** [comment]
I also tried changing that line to the format pip generates when freeing constraints.
```
fpdf @ git+ssh://git@git.cliosoft.net/HUB/pyfpdf.git@a1285edc35e75631269
```
That generated a different exception:
```
    raise LicenseCollectionError(
__main__.LicenseCollectionError: Expected a precice specification in the frozen constraint for the fpdf package but got .
```

**Comment by di** [comment]
This is because `parse_requirements` doesn't currently support requirements as URLs the same way `pip` does. In order to support this, we'd need to include something like what `pip` does here: https://github.com/pypa/pip/blob/d01dd4aba73799e6fab87e360d61bf0fcc525115/src/pip/_internal/req/constructors.py#L280-L304

**Comment by stevecj** [comment]
Are there any obstacles to cargo-culting that code into `pip-api`?

**Comment by di** [comment]
Probably no more than already exists (most of what is already here was similarly copy/pasted in).

Unfortunately I can't recall why I didn't include that functionality in the first place, my best guess is I was waiting to see if someone needed it!

**Comment by stevecj** [comment]
Well, it just became a need of mine. :grin:

We've had to make a fork of pyfpdf to use with our project, and now my scripts to extract license info from the packages is failing.

**Comment by tetsuo-cpp** [comment]
I begin taking a look at this today.

It doesn't seem super straightforward to just copy and paste things across because `pip-api` takes a different approach to parsing lines in the requirements file by leveraging `argparse`. I probably need to think about this a bit longer, but I'm considering whether the use of `argparse` is actually going to make things easier if we continue down this path of filling out support for various cases, or whether we should just rewrite this to hand parse like `pip` does.

CC: @woodruffw

**Comment by stevecj** [comment]
BTW, I did come up with a reasonable workaround for the lack of ability to parse the VCS entries yesterday, so improving this is in the "nice to have" category for me.

**Comment by woodruffw** [comment]
> or whether we should just rewrite this to hand parse like pip does.

I'm +1 on a hand-written parser, kicked off potentially by cripping `pip`'s current parser.

**Comment by tetsuo-cpp** [comment]
How do you feel about this @di?

If we anticipate having to gradually copy across chunks of the `pip` functionality, rewriting the parser to be a bit more hackable could be helpful in the long run. But if we don't need feature parity, then it might be quicker just to work with what's already there.

**Comment by di** [comment]
I'm fine with that approach as long as we ensure we're maintaining backwards-compatibility.
